'use client';

import { useEffect, useState } from 'react';
import { fetchStoredTask, fetchStoredTasks, type StoredTaskRun, type WorkingLogEntry } from '@/lib/api/agentGateway';

const safeText = (value: string | null) => (value || '').replace(/<[^>]*>/g, '').slice(0, 200_000);
export default function TasksPage({ params }: { params: { agentId: string } }) {
  const [tasks, setTasks] = useState<StoredTaskRun[]>([]); const [selected, setSelected] = useState<StoredTaskRun | null>(null); const [log, setLog] = useState<WorkingLogEntry[]>([]);
  useEffect(() => { const load = () => void fetchStoredTasks(params.agentId).then((next) => { setTasks(next); setSelected((current) => next.find((task) => task.task_id === current?.task_id) || next[0] || null); }); load(); const timer = window.setInterval(load, 5000); return () => window.clearInterval(timer); }, [params.agentId]);
  useEffect(() => { if (!selected) { setLog([]); return; } const load = () => void fetchStoredTask(params.agentId, selected.task_id).then((result) => { if (result) setLog(result.working_log); }); load(); const timer = window.setInterval(load, 5000); return () => window.clearInterval(timer); }, [params.agentId, selected?.task_id]);
  return <main className="grid min-h-[580px] overflow-hidden rounded-2xl border border-outline-variant/30 bg-surface-container-low lg:grid-cols-[340px_1fr]"><aside className="border-b border-outline-variant/30 lg:border-b-0 lg:border-r"><div className="border-b border-outline-variant/30 p-5"><h1 className="font-headline text-lg font-bold text-on-surface">Tasks & Deliverables</h1><p className="mt-1 text-xs text-on-surface-variant">Live working-log updates from this connected agent.</p></div>{tasks.length ? <div className="divide-y divide-outline-variant/20">{tasks.map((task) => <button key={task.task_id} onClick={() => setSelected(task)} className={`block w-full p-4 text-left hover:bg-surface-container-high ${selected?.task_id === task.task_id ? 'bg-primary/10' : ''}`}><p className="truncate text-sm font-bold text-on-surface">{task.title || task.task_id}</p><p className="mt-1 font-mono text-[10px] text-primary">{task.state} · {task.model}</p><p className="mt-1 text-[11px] text-on-surface-variant">{new Date(task.created_at).toLocaleString()}</p></button>)}</div> : <p className="p-5 text-sm text-on-surface-variant">No task activity received yet. Start a connected-agent task to sync its working log.</p>}</aside><section className="min-w-0 p-6">{selected ? <><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-headline text-xl font-bold text-on-surface">{selected.title || selected.task_id}</h2><p className="mt-1 text-xs text-on-surface-variant">{selected.category || 'uncategorized'} · {selected.input_tokens.toLocaleString()} tokens · {selected.latency_ms} ms</p></div><span className="rounded bg-primary/15 px-3 py-1 font-mono text-xs text-primary">{selected.state}</span></div>{log.length ? <ol className="mt-6 space-y-3 border-l border-outline-variant/40 pl-5">{log.map((entry) => <li key={entry.event_id} className="relative"><span className="absolute -left-[1.72rem] top-1 h-3 w-3 rounded-full bg-primary" /><p className="text-sm font-bold capitalize text-on-surface">{entry.phase.replace(/_/g, ' ')}</p><p className="mt-0.5 text-xs text-on-surface-variant">{entry.kind} · {entry.progress_pct ?? '—'}% · {new Date(entry.created_at).toLocaleTimeString()}</p><pre className="mt-2 whitespace-pre-wrap rounded-lg bg-surface-container-high/50 p-3 text-sm text-on-surface">{safeText(entry.markdown)}</pre></li>)}</ol> : <pre className="mt-6 max-h-[470px] overflow-auto whitespace-pre-wrap rounded-xl border border-outline-variant/30 bg-surface-container-high/50 p-5 text-sm leading-6 text-on-surface">{safeText(selected.deliverable_markdown) || 'Waiting for the connected agent to publish working-log entries.'}</pre>}</> : <p className="text-sm text-on-surface-variant">Select a task to inspect its working log.</p>}</section></main>;
}
