'use client';

import { useState } from 'react';
import { fetchRlusdAnalytics, type RlusdSnapshot } from '@/lib/api/agentGateway';

export default function RlusdPage() {
  const [data, setData] = useState<{ source: 'live' | 'stale'; warning?: string; snapshot: RlusdSnapshot } | null>(null); const [loading, setLoading] = useState(false);
  const refresh = async () => { setLoading(true); setData(await fetchRlusdAnalytics()); setLoading(false); };
  const snapshot = data?.snapshot;
  return <main className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">XRPL Testnet</p><h1 className="font-headline text-2xl font-bold text-on-surface">RLUSD Intelligence</h1><p className="mt-1 text-sm text-on-surface-variant">On-demand, ledger-indexed snapshot. A failure preserves only the last complete verified result.</p></div><button onClick={() => void refresh()} disabled={loading} className="rounded-lg bg-primary px-4 py-2 text-xs font-bold text-on-primary disabled:opacity-50">{loading ? 'Refreshing…' : 'Refresh on-chain data'}</button></header>{data?.source === 'stale' && <p className="rounded-lg border border-error/40 bg-error/10 p-3 text-sm text-error">Stale verified snapshot: {data.warning}</p>}{snapshot ? <><p className="font-mono text-xs text-on-surface-variant">Ledger {snapshot.ledger_index} · {new Date(snapshot.evaluated_at).toLocaleString()}</p><div className="grid gap-4 md:grid-cols-3"><Card label="RLUSD circulating" value={snapshot.supply.circulating || 'Unavailable'} /><Card label="Trustlines observed" value={snapshot.trustlines.lines?.toLocaleString() || 'Unavailable'} /><Card label="Orderbook offers" value={Array.isArray(snapshot.movement.orderbook) ? snapshot.movement.orderbook.length.toLocaleString() : 'Unavailable'} /></div><section className="rounded-2xl border border-outline-variant/30 bg-surface-container-low p-5"><h2 className="font-headline text-base font-bold text-on-surface">Verified source context</h2><p className="mt-2 text-xs text-on-surface-variant">Issuer: {snapshot.supply.issuer || 'not configured'} · Ledger hash: {snapshot.ledger_hash || 'not provided'}</p></section></> : <section className="rounded-2xl border border-dashed border-outline-variant/40 p-8 text-center text-sm text-on-surface-variant">Refresh to query the configured XRPL Testnet issuer.</section>}</main>;
}
function Card({ label, value }: { label: string; value: string }) { return <section className="rounded-2xl border border-outline-variant/30 bg-surface-container-low p-5"><p className="text-xs text-on-surface-variant">{label}</p><p className="mt-2 font-mono text-2xl font-bold text-primary">{value}</p></section>; }
